### ISSUE TITLE
RDExporter base string

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#1]
This should probably be the same as the name of the model (or something like that, but filtered/mangled). Right now it's just "TestModel".

**Comment by danionita** [comment]
What is the base string?

**Comment by bobismijnnaam** [comment]
It's the base string used for the RDF model. (See the definition of the base variable in RDFExport). As of 7820c575d6e2e91604d637be9158209c0b41696d RDFExport uses the title of the model instead of TestModel for the base string.
