### ISSUE TITLE
E3Graph correctness

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#13]
The editor should ensure that a valuemodel is always correct. For example, every value interface should have every valueport and connection dot connected to something else. Otherwise the model is invalid. The editor should do checking to inform the user of invalid things, and prevent launching the e3fraud module if that is the case.

**Comment by bobismijnnaam** [comment]
We could also let all "gates" light up red if they should be connected

**Comment by bobismijnnaam** [comment]
As of  55332f3f69626dbdbbc2707ce057291977f37b31 value ports/signal dots light up red if they are not connected.

**Comment by bobismijnnaam** [comment]
As of 3125f54c50b8885fe4b1d5f614b65ce22fc6826a the editor now also first asks the user if the user wants to continue when the model is invalid when fraud generation is clicked.

**Comment by danionita** [comment]
niiice :)
