### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#14]
Right now there is zero custom styling in the editor. Ideally:
- Not too much format properties
- Preferences for coloring the graph in a separate file
  - text, background, etc.
  - Font size
  - Edges also need a label
- Be able to make simple changes (make one specific edge red)
- Save color/style schemes separately
- Possibly bundle style scheme with value model?

**Comment by danionita** [comment]
I'd go with: folder where default style files are stored on first launch. Menu item by which any style file in the folder can be selected or applied. Individual changes to specific elements saved bundled with value model.

**Comment by bobismijnnaam** [comment]
So what kind of specific customization features do we want to offer to the users? Just background colors, font sizes/styles, what else?

**Comment by danionita** [comment]
Background color and font size should be sufficient for now. Maybe font
color too.

**Comment by bobismijnnaam** [comment]
Did background color, font size, font color as of  652743d9913a70e5be0ce5977696f3b287c76741. Needed to pull some funky tricks to get the marketsegment entity to behave, but it worked :D Next up, probably styles that the user can pick for the overall look of the model. Oh, and probably should add edge (color/thickness?) styling as well.

**Comment by danionita** [comment]
Edge color is enough.

**Comment by bobismijnnaam** [comment]
So right now I've got themes partially working. When the user selects a specific color for an actor, and then selects another theme, the actor which was just colored a specific color retains its specific color. So if I make an actor pink, and then select the E3Mono style, the actor will remain pink, while all the other actors will be extra grey. Is this desired behaviour or do we want to delete specific settings when a new theme is selected? Right now this behaviour seems consistent, which would make development easier, but I'm not entirely sure so it probably needs some work anyway to cover all the edge cases.

**Comment by danionita** [comment]
Imo applying a theme should override all applicable element colours.

**Comment by bobismijnnaam** [comment]
Okay, situation atm:
- User can select from two styles by default: e3style and e3mono. These are located in the e3tool's resources in the jar
- The tool reads from "C:/users/bob/e3tool/styles" for any user-supplied styles (of course the user dir varies per user)
- The style is included when a model is saved
- Selecting a new style erases all specific customizations (a random purple background color)
- The style format is documented in E3style.java

Things not supported atm:
- Style changes cannot be undone (e.g. going back to the previous style using ctrl+z). I'm not sure if it's possible to support this but I think it should be possible, we'll see.
- If the user downloads a theme from the internet with the same name as one he has made himself, he has to delete his own theme to use the other one. Pretty fundamental problem. Users could solve this by prefixing their own themes with their name or something. Is however still a concern to us to some extent.
- Maybe a "create blank style" button somewhere that creates a default style in the users e3tool/styles directory? Such that the user does not have to copy paste things around and only has to edit the thins he wants to change.
- I'd like a preview box when selecting a theme. This, combined with a warning, might eliminate the need to undo theme changes (but I still think it should be supported)

I guess that's it. It should be thoroughly tested but I haven't been able to find any bugs. For now I'll only look at the first point. The other 3 I'll work on if @danionita wants them too.

**Comment by bobismijnnaam** [comment]
As of 925746048bf441cebab497fe289e68310c8983f3 the user can undo theme changes.

**Comment by danionita** [comment]
Great progress!

> - Style changes cannot be undone (e.g. going back to the previous
>   style using ctrl+z). I'm not sure if it's possible to support this but I
>   think it should be possible, we'll see.
> 
> I see you' added this. Great.
> - If the user downloads a theme from the internet with the same name
>   as one he has made himself, he has to delete his own theme to use the other
>   one. Pretty fundamental problem. Users could solve this by prefixing their
>   own themes with their name or something. Is however still a concern to us
>   to some extent.
> 
> No problem. The tool would have to become a lot more mainstream before
> this becomes an issue, and even then, new themes should have new names :)
> This is a huge improvement anyway.... Consider the old tool supported only
> one style file, which _had_ to be overwritten if you wanted any changes to
> apply to an entire model. (also re-launching the tool and going through
> some weird  process to get it to apply).
> - Maybe a "create blank style" button somewhere that creates a default
>   style in the users e3tool/styles directory? Such that the user does not
>   have to copy paste things around and only has to edit the thins he wants to
>   change.
> 
> How about just a "save style" button, which save whichever global
> preferences the user currently has as a style file in the .../styles
> folder? Wouldn't that be easier and more intuitive?
> - I'd like a preview box when selecting a theme. This, combined with a
>   warning, might eliminate the need to undo theme changes (but I still think
>   it should be supported)
> 
> I think a photo is sufficient, right?
> An even fancier way would be to have a mini-view, with a 2 actor model
> included in the window which updates when selecting a theme.

BTW, I've sent out the tool to D-Telekom last week.

**Comment by bobismijnnaam** [comment]
> > - Maybe a "create blank style" button somewhere that creates a default
> >   style in the users e3tool/styles directory? Such that the user does not
> >   have to copy paste things around and only has to edit the thins he wants
> >   to
> >   change.
> > 
> > How about just a "save style" button, which save whichever global
> > preferences the user currently has as a style file in the .../styles
> > folder? Wouldn't that be easier and more intuitive?

Depends. To make a feature like that useful we would also need some
"structural" editing buttons. Like "set default actor color" or "set
default font color". We could have something like that, though. What kind
of structural settings do we want in that case? Just default colors of
value activies/market segments/actors, connection elements, and value
exchanges, and maybe default font colors and font sizes? Maybe make
categories for value exchange labels and entity labels? That way e3tool
comes with a built-in "theme editor".

Altough I'm not sure if this has a very high priority. I think multi select
is more important and harder than this.

> > - I'd like a preview box when selecting a theme. This, combined with a
> >   warning, might eliminate the need to undo theme changes (but I still
> >   think
> >   it should be supported)
> > 
> > I think a photo is sufficient, right?
> > An even fancier way would be to have a mini-view, with a 2 actor model
> > included in the window which updates when selecting a theme.

Yeah, we could show some default model (one of the examples?) that uses
every styling feature with the styling applied. Shouldn't take too much
time.

> BTW, I've sent out the tool to D-Telekom last week.

Looking forward to their response!

**Comment by danionita** [comment]
Hi Bob,

Since individual elements can be customized easily and custom themes can be
defined via the style files, that is enough for now.

Best regards,
Dan Ionita

**Comment by danionita** [comment]
Jaap mentioned that, since the old tool had a "theme editor", we should have one too.
Therefore, we need:
- Either "undo" style application or "preview" style. Ideally, both.
- A window where the user can change the style of individual element. I think we can use the same thing as the old tool: a "multi-dialog" where the user can select element classes to edit via a drop-down (see below, but no need to support all those customizations: just color, text color, text size and border color when applicable). This window should also have the ability to save the current style to a style file in the style folder.

Sidenote: the preferences window in the old tool looks rather "standard". Maybe we could find something similar?

![image](https://cloud.githubusercontent.com/assets/11060388/19393995/75f09192-9237-11e6-9e2e-ffbb34a0fe77.png)

**Comment by bobismijnnaam** [comment]
Well, I found this: http://jfontchooser.osdn.jp/site/jfontchooser/screenshots.html Altough it does just te font, it might do for text.

Found it on github: https://github.com/dheid/fontchooser with appropriate maven thing: http://search.maven.org/#artifactdetails%7Cio.github.dheid%7Cfontchooser%7C1.1%7Cjar

**Comment by bobismijnnaam** [comment]
It looks acceptable: 
![image](https://cloud.githubusercontent.com/assets/3082344/21080656/dc8a17e8-bfb4-11e6-9e8b-6870bada2a8d.png)

**Comment by danionita** [comment]
Looks nice. I assume:
- you will add the existing text color changer
- there will be two versions of this: one for individual elements, and one for the theme (all elements of each type).

**Comment by bobismijnnaam** [comment]
Right on!

Op 14 dec. 2016 1:30 p.m. schreef "danionita" <notifications@github.com>:

**Comment by bobismijnnaam** [comment]
Progress update: as of 227a4f137764b7a1d2a9e3fd714d47cf5f021ce4 I have improved the style selector to be more modular & also support stroke color. Next I will integrate it with our custom styling plan, such that the user can change all the actors, ms's, etc.

**Comment by bobismijnnaam** [comment]
Should work as of 3bd4465da8a0e2c868a188677f38a97d6efabe7d. @danionita Let me know if this suffices!
