### ISSUE TITLE
Rotating and/or gates (like in the old editor) should be possible

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#18]

**Comment by bobismijnnaam** [comment]
Rotating is already possible. Does this mean flipping is therefore not needed?

**Comment by danionita** [comment]
Didn't know rotation is possible. If by flipping you mean mirroring, then
it is not needed. Almost the same effect is achievable by a 180 degree
rotation.

**Comment by bobismijnnaam** [comment]
Great
