### ISSUE TITLE
Ability to name and rename tabs and/or graphs

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#21]

**Comment by bobismijnnaam** [comment]
You can now rename tabs/graphs (same thing at the moment) in the model menu as of 79fd26045cd57032894c341715339056d3eacfe8. Is that sufficient? I was thinking maybe a right mouse menu on the tab is also nice, or maybe if you doubleclick on a tab it allows you to change the tab name as well.

**Comment by danionita** [comment]
I think it's ok for now. Double-click is a nice-to-have but not necessary
atm.

**Comment by bobismijnnaam** [comment]
Fixed as of dc815ec95fad1b2038022f4a95957e1ed0d97f4c. Double clicking a graph tab title allows you to change it in-place.
