### ISSUE TITLE
cannot edit edge labels

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#22]

**Comment by bobismijnnaam** [comment]
If you right click, edit e3properties, on the valueexchange you can change the label in the window that appears. Do we need to make this clearer?

**Comment by danionita** [comment]
We should be consistent. For actors, labels can be edited by
Double-clicking. Why not do the same for edge labels?

**Comment by bobismijnnaam** [comment]
Alright, I'll have a try at enabling that

**Comment by bobismijnnaam** [comment]
Fixed as of b61bbbb889e386e0945370a6a62ddb56fdb21ee3.
