### ISSUE TITLE
Adjust "OCCURRENCES" formula after getting an e3fraud model from the generator

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#3]

**Comment by bobismijnnaam** [comment]
Asked @danionita, and this should happen automatically (since the fraud generator just changes the formulas, so it should propagate to new models just fine).

**Comment by danionita** [comment]
Might be some confusion here. TBH,  I don't remember what I meant with this
issue.
If it is that the model returned by the e3fraud generator has a changed
occurrences formula, then I should take care of this in the e3fraud code.

**Comment by bobismijnnaam** [comment]
Yeah I added this issue at some point. First I thought I had to set the
occurrences variable but then you said it was done in the generation code.
So 😅
