### ISSUE TITLE
Sometimes "not a valid proportion is triggered" unnecessarily 

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#33]
(e.g. 6666666666)

**Comment by bobismijnnaam** [comment]
So do we want to handle arbitrarily big integers, or do we just say "proportion too big" when this happens? (I'll go with the latter for now)

**Comment by bobismijnnaam** [comment]
Fixed as of e9eaaac624162c4619fda44ec4a6b0ac6a14c559.

**Comment by danionita** [comment]
Would be nice to make it somewhat more transparent to the user. Maybe
change the warning message to "enter a number between x and y". Also, I
think maybe we should support sub-unitary numbers too, as that's what users
intuitively interpret "fraction" as.
