### ISSUE TITLE
Apply correct formatting when loading a model

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#36]
When a model is loaded, its styling is included with the file. So let's say someone saved a file last week, and that we changed the size of start/end signals yesterday. If that someone loads his model today, he will still get the big start/end signals (instead of the small start/end signal included with the editor). This can be solved by either using a format that doesn't include formatting (which we'll have to make ourselves -.-') or do a pass over every loaded graph to make sure it is styled correctly. The second option is probably the appropriate one, since we already have a good format for saving models now. 

(Or we could only make visual changes every major editor release, and mark the save files from different releases as "incompatible". Brr.)

**Comment by danionita** [comment]
This is not a bug, but a feature: any visual customization is carried over on save/load, and the user can manually change the style of any model via the dedicated option, which is enhancement #14
