### ISSUE TITLE
Combine value object/value exchange labels in some way

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#4]
Right now they are separate which feels very clunky to work with

**Comment by bobismijnnaam** [comment]
Right now they are combined in the label, and the user can insert newlines or whitespace to control the presentation somewhat. As it puts quite a strain on the editor to implement an extra label for an object, I'd prefer if we kept using this approach.

**Comment by danionita** [comment]
Let's stick with this
