### ISSUE TITLE
implement “Show/hide all labels”

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#44]

**Comment by bobismijnnaam** [comment]
Do you mean the "Show/hide name" context menu from the value exchange context menu? Cause that one works. Or the "show/hide all labels" drop down menu item from the toolbar?

**Comment by danionita** [comment]
Not sure, this is the quote I received from  one of our testers. Is the
show/hide all labels inactive?

**Comment by bobismijnnaam** [comment]
Yeah, the show/hide buttons are not yet implemented. If you bump them up on
the milestone list monday I'll get to them the next time I'll work.

**Comment by bobismijnnaam** [comment]
Done as of  266b4da1e471c3278c56cae66b3a222e8194b5ad.
