### ISSUE TITLE
Add support for Market Segments in e3fraud computation

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#45]

**Comment by bobismijnnaam** [comment]
I think there is actually a comment about this in RDFExport.java. there
seems to be a e3value rdf attribute missing. Can you check @danionita? It's
somewhere in the middle :p

Op 12 aug. 2016 11:00 a.m. schreef "danionita" notifications@github.com:

**Comment by danionita** [comment]
Found the comment but not sure what it's about.
An MS is not a sub-type of actor. It is a separate element. Essentially,
there are two types of actors: Actors and Market Segment. An actor usually
represents a company, while a market segment usually represents some
customers. Therefore, value activities can only be part of actors, but
market segments have a COUNT formula.
NB: the e3value vocabulary class in the repo is original, not one I
created. Therefore, we can take is as a standard.

Best,
dan

**Comment by danionita** [comment]
Scratch that. Upon further inspection of the e3value meta-model it seems I
was wrong. A Market segment _is,_ literally, a set of actors (denoted by
 ms_consists_of_ac). That means they can in fact contain value activities
and behave exactly like any actor.

I will send an e-mail to Jaap to try and shed some light on this.

**Comment by bobismijnnaam** [comment]
As of 38785c0ecbb54afc47190ec0238ec9a459b7581e there is market segment support, I think...
