### ISSUE TITLE
e3fraud Generation/Ranking crashes for large models

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#46]

**Comment by bobismijnnaam** [comment]
No error message :(?

Op 12 aug. 2016 11:01 a.m. schreef "danionita" notifications@github.com:

**Comment by danionita** [comment]
Doesn't seem to be the case anymore. Successfully generated >8000 fraud models from a large value model, although it did take a few minutes.
In the future, we might consider speeding it up.
