### ISSUE TITLE
Incorrect edge snapping (helper highlighting)

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#47]
When drawing an edge, all kinds of ports are highlight as if a connection would be possible.  Only ports to which a connection is really possible should light up.
E.g. when drawing a dependency path, ports (triangles light up). Conversely, when drawing a transfer, start/end nodes, and/or nodes and the black dots on value interfaces all light up.

**Comment by bobismijnnaam** [comment]
Fixed as of d7ff88402bea5addc69f2b08f6dfad0f03b4e467.
