### ISSUE TITLE
Make it easier to assign value objects to transfers

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#50]
The previous editor allowed this:
While ObjectsEditor dialog was opened and a value object was selected, clicking on a transfer would add/replace or remove that value object to the respective transfer..

**Comment by bobismijnnaam** [comment]
This would be nice to have to "batch-edit" several transfers and assign value objects to a bunch of transfers.

**Comment by bobismijnnaam** [comment]
Implemented as of 0996f8f78ab8e0f6e6ae19ccb33af32c0b661de2.
