### ISSUE TITLE
Implement vp_second_connects_ve 

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#53]
When a value interface is connected to both an outside and an inside value interface, proper RDF attributes should be generated (using vp_second_connects_ve and its inverse. See generated RDF from the old editor for an example). See the image for an example.

![nested](https://cloud.githubusercontent.com/assets/3082344/17741823/fead74ae-649d-11e6-9aa8-673fcbe769fc.png)

**Comment by bobismijnnaam** [comment]
Hmm, when you create this configuration and export it in the old editor, the old editor also starts using `ve_has_first_vp`, `ve_has_second_vp`, and `vp_first_connects_ve`. What do these attributes mean? I have a hard time figuring it out from the rdf.

**Comment by danionita** [comment]
No idea... Let's look at this together when I am back.

**Comment by danionita** [comment]
Deeper investigation seems to have revealed the following:
ve_has_first_vp = ve_has_in_po
ve_has_second_vp = ve_has_in_po
vp_second_connects_ve = vp_in_connects_ve
vp_first_connects_ve = vp_out_connects_ve
The former seems to replace the latter when the respective VP has VEs on both sides, or when the respective VE connects an internal element (value-activity or sub-actor) to its parent.
![image](https://cloud.githubusercontent.com/assets/11060388/20524907/256a7ec8-b0bd-11e6-8524-2140f63fbd6a.png)

**Comment by bobismijnnaam** [comment]
That seems consistent, altough I have found a case where we get slightly different results.

![image](https://cloud.githubusercontent.com/assets/3082344/21080122/5720511a-bfa7-11e6-9dc9-787755a8d4a7.png)

What seems to happen here the "center" ve (ve1 & ve2) seem to give "normal" (vp_in_connects_ve, vp_out_connects_ve) attributes to the value ports. The "outer" ve (ve3, ve4 on both sides) seem to give "weird" (vp_first_connect_ve, vp_second_connect_ve) attributes to the value ports. So in this case, a value port has "normal" attributes on one side, and "weird" ones on the other. What I'm having trouble with is that in your case, vp3 & vp4 have "weird" attributes on both sides, but in my case, one side has "weird" attributes and one side has "normal" attributes. This is so strange I'm sure I must be missing something. Can you have a look at this situation's RDF as well and see if you agree with me?

**Comment by bobismijnnaam** [comment]
Annotated picture to illustrate my point more clearly:

![image](https://cloud.githubusercontent.com/assets/3082344/21080211/ee87b870-bfa9-11e6-9a93-f589f8bba8c4.png)

As you can see in the center the conventions first/second and in/out are intermingled, while in your case they are not. I'm having trouble deciding when to apply the first and when the second.

**Comment by bobismijnnaam** [comment]
Hmmm, I annotated your situation as well, and I get a different result:

![image](https://cloud.githubusercontent.com/assets/3082344/21080287/9d43d550-bfab-11e6-803a-e4b20c14a9db.png)

It seems to resonate with my previous observation/confusion.

**Comment by bobismijnnaam** [comment]
I think the rule is:

- If the parents of the two containers (actor/market segment/value activity containing the value port) is the same, or both are top level containers, then just use in_connects_ve, ve_has_out_po, etc. (as is the case in the bottom value exchange in the previous example)
- If one of the containers contains the other container (as is the case in the top value exchange in the previous example) use ve_has_first_vp, vp_second_connects_ve, etc.

**Comment by bobismijnnaam** [comment]
Hey, another funny thing: if you take my last example and try to assign a value object to the inner or outer value exchanges, the editor assigns the value object to both the inner and the outer value exchanges. I guess that makes sense, to some extent, but I'll have to implement that as well.

**Comment by bobismijnnaam** [comment]
Implemented the correct attributes in RDFExprt line 486-something as of commit 4e267c66241922bfd0fc90ccf82c722773dbd626. The normal example works; I'm not sure how we can test the "doubly value exchanges". Atm the fraud generator does not work with doubly value exchanges.

**Comment by danionita** [comment]
Working on handling "doubly" exchanges. Will test next week.

**Comment by danionita** [comment]
Spotted an error while implementing handling of "doubly" exchanges by fraud generation:
Some interfaces (it seems to be the ones at the "bottom end" of a doubly exchange) do not get assigned the correct "de_down_ce" attribute connecting them to the next element. See two examples below (problem interface highlighted in green):

![image](https://cloud.githubusercontent.com/assets/11060388/21324904/ff42f26c-c623-11e6-801d-9b6d74dd67d8.png)


![image](https://cloud.githubusercontent.com/assets/11060388/21324596/b9ad6cf6-c622-11e6-9ba6-46af6e3a9921.png)

**Comment by bobismijnnaam** [comment]
@danionita It seems your example works now. The reason was quite stupid:  I had not yet implemented doubly ve's in the RDF exporting logic. Let me know if it works correctly now.
