### ISSUE TITLE
Integrate legacy e3value functionality

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#55]
The following modules need to be broken off the old e3value tool and integrated into the new tool.
Currently waiting for the developers of e3value to provide this code.

**Comment by bobismijnnaam** [comment]
Stuff I had to do before I got a sensible error message:
- Replaced - with _ (s/-/_/g)
- Added xml header
- Added doctype header
- Did the weird thing with the &'s in the rdf:RDF tag
- Removed the weird doctype and inlined the urls again (with correct dashes)

**Comment by bobismijnnaam** [comment]
Then I added valuations and value transactions and the simple test I implemented generated an excel sheet.

**Comment by danionita** [comment]
Do you mean to say that after you did all that, the NCF parsed the RDF
correctly and completely?
Does this mean it is fixed now or was this just a diagnosis?
What is "the weird thing with the &'s in the rdf:RDF tag"?

**Comment by bobismijnnaam** [comment]
This was all just to find an example of an rdf model that works. So yeah, a diagnosis I guess. And indeed after I did all that the NCF parsed the rdf completely. The RDF was still generated by the old editor though, not the new one.

The weird thing is the doctype declaration between the xml header and the rdf tag.

**Comment by bobismijnnaam** [comment]
The original editor exports a `vt_has_fraction="1"` property when you add value transactions. However our ontology does not have any `vt_has_fraction` property (that is, `E3value.vt_has_fraction` does not seem to exist). Should we add it by hand?

**Comment by bobismijnnaam** [comment]
Well, turns out Jaap's code barfs when the vt_has_fraction property is not present. So I'm just gonna add it now (ProfGenerator.java:2110)

**Comment by bobismijnnaam** [comment]
NCF module purrs without errors. No clue if the output is correct though (see slack for debug output & xls). As of: bdee35738f6f912c2ca0bcf851ddbdb257c4da30.

**Comment by danionita** [comment]
Somehow I missed these last updates. All looks good.
The transaction editor (issue #90 should allow the user to change the vt_has_fraction property
