### ISSUE TITLE
Bug in conversion from fraud to value

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#56]
When a model is converted from fraud to value with E3Graph's toValue() method, at the moment all hidden transfers are made unhidden. But should they instead be deleted? Since hidden transfers tend to be added by the fraud generation module, the original value model tends not to have them.

**Comment by danionita** [comment]
Indeed, hidden transfers should be removed, non-occurring transfers should be made occurring and colluding actors should be separated.

**Comment by bobismijnnaam** [comment]
Fixed as of 947a7ca2048dda25f2dfd002840f606afe6e3e0e.
