### ISSUE TITLE
Value propagation from ports to edges

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#60]
We keep forgetting to talk about this, but I'm not sure if I implemented it at some point, so lets document it to get rid of my doubt. What needs to be propagated from the value ports to the edges, and when? When the user edits the properties of a value exchange, and one of the value ports has valuation set, should the property window show that valuation? If a value exchanges has the valuation set, should both ports "inherit" this valuation setting when editing their properties? Should this inheritance also be applied when exporting to RDF?

**Comment by danionita** [comment]
As far as I know, you'e implemented the second option a while ago.
That is, if the valuation of a value exchange is changed, it should
propagate to both its ports. If the valuation of a port is changed, it only
applies to that port.

**Comment by danionita** [comment]
This is now broken again.

Desired behavior: if the valuation of a value exchange is changed, the valuation should immediately 
propagate to both its ports. If the valuation of a port is changed, it only applies to that port.

Current behavior: when pressing the fraud generation or profitability computation button, the valuation of value exchanges are propagate its ports, but the RDF that is generated does not include this. Also, only numerical formulas are propagated, not expressions.

**Comment by bobismijnnaam** [comment]
I found how I (incorrectly) implemented it:

```
[in RDFExport.java]
// Propagate valuation from edge if vp valuation == 0
if (value.formulas.getOrDefault("VALUATION", "0").equals("0")) {
    value.formulas.put("VALUATION", veInfo.formulas.getOrDefault("VALUATION", "0"));
    res.addProperty(E3value.e3_has_formula, "VALUATION" + "=" + value.formulas.get("VALUATION"));
}
```

So when a value port's valuation is zero, it copies the valuation from its connected value transfer. This should not edit the original model (the one in the editor), so that's a bug. But the semantics are different from the previously described desired behaviour (apply as soon as the valuation on a value transfer is changed). I'll implement the desired behavior now, but if you want the other way it's easy to revert.

**Comment by bobismijnnaam** [comment]
Implemented as of d2b17d595021cb65d0a741f44d80524d34aac2c3.

**Comment by bobismijnnaam** [comment]
Does this fix the issue @danionita?

**Comment by danionita** [comment]
Yes, seems to work now.
However, we need to trigger this when loading the example models too. Right now, fraud generation for flat-rate does not work because this does not take place.

**Comment by bobismijnnaam** [comment]
I'm on it :p
