### ISSUE TITLE
Feedback issues from Roel

### ISSUE THREAD

**Issue by bobismijnnaam** [danionita/e3tools#61]
> Some small issues on the current version;
> -          When editing the e3fraud model (e.g. after right click and select fraud
>   – colluding) it is not anymore possible to open the fraud generation window.

I think this has to do with the fact that his model was a fraud model, and analysis of a fraud model is disabled. At the moment a window appears asking if conversion to a value model is ok. If that's enough this problem is not a problem anymore.

> -          It is annoying to users if they want to save (not save as) but always
>   the dialog box pops up  and again I have to parse through the directories to
>   replace it. This is tough to frequently save updates.

I think @danionita implemented "file remembering" s.t. when you save to a file, the editor will keep saving to that file

> -          Sometimes when I click to show the labels, it doubles the value object
>   types – Like e.g. [Money][Money]

I fixed this some time ago, shouldn't be a problem.

> -          I was trying to model the roaming scenario (see the attachment) but I
>   could not generate scenarios because I can’t choose the main actor from the
>   ‘fraud generation’ window. So I can’t evaluate the result neither.

This is because he only uses value activities. Somehow these don't show up in the fraud editor. This should either be documented in the wiki, and an error message when no actors are detected should be shown when the fraud window opens. Or we should just fix this s.t. value activities should also be able to be picked as root for the analysis (this depends on e3value semantics however).

So all in all this stuff should be easy to fix :)

**Comment by danionita** [comment]
Hi Bob,

I'm sorry, I though I already replied to this. I'm behind the Great Chinese
Firewall so accessing my e-mail is very tricky and some e-mails don't seem
to go through...

All your replies are on point. I've already explained points 1 and 4 to the
tester. I will fix file remembering.

Best,
Dan
