### ISSUE TITLE
Enforce non-null , unique naming on ALL elements.

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#66]
Elements with pre-defined names (such as actors) have a (1), (2), ... appended.
Elements with default null names get `2char+uid` as name, where 2char is a 2-character abbreviation of its type.

**Comment by bobismijnnaam** [comment]
Also, the only allowed letters are alphanumeric. So, a-z, A-Z, 0-9. (from the metalanguage pdf)

**Comment by bobismijnnaam** [comment]
Oh man. Apparently according to the manual spaces are not allowed in names. However for markup purposes they are used sometimes...? Maybe we should allow spaces in this notation: `'Subscription fee'.VALUATION`?

**Comment by danionita** [comment]
That explains why names were kept separate from labels in the old tool I
guess.
I think there is no reason for us to enforce this though.

Best regards,
Dan Ionita

**Comment by bobismijnnaam** [comment]
As of a commit I made this weekend unique names are enforced in the editor.
