### ISSUE TITLE
Show object type in e3properties window

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#69]
Due to the small size of some elements, it is possible to accidentally open the properties of the wrong element. Right now it is impossible to know which element you are currently editing if it does not have a given name.
It would be therefore nice to add a new column, next to ID, that indicates what type of element this is.

**Comment by bobismijnnaam** [comment]
Implemented as of e6752fa5cc7976139c7e93c74d521249f5fe5ab5. As a row though, as that's how the properties window is structured. If it really _has_ to be  a column it'll take another commit :p

**Comment by danionita** [comment]
I meant row, obviously :)

**Comment by bobismijnnaam** [comment]
:p
