### ISSUE TITLE
Double-click to open properties window

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#70]
Right now double-clicking any element will either do nothing, or start editing the label.

A better option would be:
- double-clicking the label starts editing the label
- double-clicking the object opens the properties window (where one can also change the label)

**Comment by bobismijnnaam** [comment]
This is hard to do in jgraphx. What about making a hotkey for the e3properties window? F3 or something? Or maybe double right mouse click?

**Comment by danionita** [comment]
Ok. Then let's leave it as it is for now.
