### ISSUE TITLE
OK/Cancel option on e3properties window

### ISSUE THREAD

**Issue by danionita** [danionita/e3tools#80]
Playing around with the tool, I've ended up in situations where I was unable to close the properties window because either I had to give a (unique) name to the object despite not changing the name or getting a protected attribute error despite not adding any attributes. 

Therefore, I think there should be a OK/CANCEL option for this window, with X cancelling all changes. This also helps undo undesired changes (such as overwriting a complex expression).,

**Comment by bobismijnnaam** [comment]
Fixed as of c50d138c74990bbf956e6813ef8f23ed060bdd1a.
